---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v2.5.0
    hooks:
      #- id: trailing-whitespace
      #  files: \.(js|json|rb|md|py|sh|txt|yaml|yml)$
      - id: check-case-conflict
      #- id: check-json
      #- id: end-of-file-fixer
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.21.0
    hooks:
      - id: yamllint
  - repo: https://github.com/willthames/ansible-lint.git
    rev: v4.2.0
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
